name: Playwright Tests
trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18'
    displayName: 'Install Node.js'
  - script: npm ci
    displayName: 'npm ci'
  - script: npx playwright install --with-deps
    displayName: 'Install Playwright browsers'
  # - script: npm i -D @playwright/test allure-playwright
  #   displayName: 'Install allure-playwright'
  # - script: npm i -g allure-commandline --save-dev
  #   displayName: 'Install allure-commandline'
  - script: npx playwright test
    displayName: 'Run Playwright tests'
  # - script: allure generate allure-results -o allure-report --clean
  #   displayName: 'generate allure-report'
    env:
      CI: "true"